const data = {
  products: [
    {
      id: 1,
      name: 'MacBook M1',
      slug: 'macbook-m1',
      category: 'Laptops',
      image: '/images/products-img01.jpg',
      price: '990,000',
      brand: 'Apple',
      rating: 4.0,
      numReviews: 10,
      countInStock: 2,
      description: 'One of the best Laptops out here',
    },
    {
      id: 2,
      name: 'iwatch',
      slug: 'i-watch',
      category: 'Wrist watch',
      image: '/images/products-img02.jpg',
      price: '13',
      brand: 'Apple',
      rating: 3.8,
      numReviews: 12,
      countInStock: 10,
      description: 'Nice watch and smart too',
    },
    {
      id: 3,
      name: 'Bond Shirt',
      slug: 'bond-shirt',
      category: 'Clothes',
      image: '/images/products-img07.jpg',
      price: '30',
      brand: 'LOUIS VUITTON',
      rating: 4.0,
      numReviews: 15,
      countInStock: 20,
      description: 'A popular Shirt',
    },
    {
      id: 4,
      name: 'Bels Skirt',
      slug: 'bels-skirt',
      category: 'Clothes',
      image: '/images/products-img08.jpg',
      price: '60',
      brand: 'PRADA',
      rating: 4.0,
      numReviews: 14,
      countInStock: 10,
      description: 'A popular Skirt',
    },
    {
      id: 5,
      name: 'Little Black',
      slug: 'little-black',
      category: 'Clothes',
      image: '/images/products-img09.jpg',
      price: '10',
      brand: 'CHANEL',
      rating: 4.0,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Clothe',
    },
    {
      id: 6,
      name: 'Polo Loco',
      slug: 'polo-loco',
      category: 'Clothes',
      image: '/images/products-img010.jpg',
      price: '10',
      brand: 'RALPH LAUREN',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Polo',
    },
  ],
};

export default data;
