import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'Dave',
      email: 'davy@cb.com',
      password: bcrypt.hashSync('test1234'),
      isAdmin: true,
    },
    {
      name: 'May',
      email: 'mary@cb.com',
      password: bcrypt.hashSync('test4321'),
      isAdmin: false,
    },
  ],
  products: [
    {
      id: 1,
      name: 'MacBook M1',
      slug: 'macbook-m1',
      category: 'Laptops',
      image: '/images/products-img01.jpg',
      price: 990000,
      brand: 'Apple',
      rating: 4.0,
      numReviews: 10,
      countInStock: 2,
      description: 'One of the best Laptops out here',
    },
    {
      id: 2,
      name: 'iwatch',
      slug: 'i-watch',
      category: 'Smartwatches',
      image: '/images/products-img02.jpg',
      price: 15000,
      brand: 'Apple',
      rating: 3.8,
      numReviews: 12,
      countInStock: 10,
      description: 'Nice watch and smart too',
    },
    {
      id: 3,
      name: 'Bond Shirt',
      slug: 'bond-shirt',
      category: 'Clothes',
      image: '/images/products-img07.jpg',
      price: 3400,
      brand: 'LOUIS VUITTON',
      rating: 4.0,
      numReviews: 15,
      countInStock: 20,
      description: 'A popular Shirt',
    },
    {
      id: 4,
      name: 'Bels Skirt',
      slug: 'bels-skirt',
      category: 'Clothes',
      image: '/images/products-img08.jpg',
      price: 5000,
      brand: 'PRADA',
      rating: 4.0,
      numReviews: 14,
      countInStock: 10,
      description: 'A popular Skirt',
    },
    {
      id: 5,
      name: 'Little Black',
      slug: 'little-black',
      category: 'Clothes',
      image: '/images/products-img09.jpg',
      price: 4200,
      brand: 'CHANEL',
      rating: 4.0,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Clothe',
    },
    {
      id: 6,
      name: 'Levy 4.0',
      slug: 'levy',
      category: 'Phone Accesories',
      image: '/images/products-img03.jpg',
      price: 25000,
      brand: 'SAMSUNG',
      rating: 4.5,
      numReviews: 10,
      countInStock: 10,
      description:
        'Headset for phones and laptops with good sound and cancelling system',
    },
    {
      id: 7,
      name: 'Polo Loco',
      slug: 'polo-loco',
      category: 'Clothes',
      image: '/images/products-img010.jpg',
      price: 4000,
      brand: 'RALPH LAUREN',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Polo',
    },
    {
      id: 8,
      name: 'EOS 5D',
      slug: 'eos-5d',
      category: 'Camera',
      image: '/images/products-img04.jpg',
      price: 890000,
      brand: 'CANON ',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Best Camera for best views you can get in beyond 3D',
    },
    {
      id: 9,
      name: 'Series 7',
      slug: 'series-7',
      category: 'Smartwatches',
      image: '/images/products-img05.jpg',
      price: 19800,
      brand: 'Z36 ',
      rating: 3.5,
      numReviews: 4,
      countInStock: 12,
      description: 'High quality waterproof bluetooth smart watch',
    },
    {
      id: 10,
      name: 'PS 5 Controller',
      slug: 'ps-5-controller',
      category: 'Games',
      image: '/images/products-img06.jpg',
      price: 30800,
      brand: 'PLAYSTATION ',
      rating: 4.5,
      numReviews: 15,
      countInStock: 30,
      description: 'Best quality controller for your gaming experience',
    },
    {
      id: 11,
      name: 'F1 Joggers',
      slug: 'f1-joggers',
      category: 'Clothes',
      image: '/images/products-img011.jpg',
      price: 19800,
      brand: 'PUMA ',
      rating: 4.5,
      numReviews: 12,
      countInStock: 30,
      description: 'Nicest joggers out here, thick and comfy',
    },
    {
      id: 12,
      name: 'Coffee Maker',
      slug: 'coffee-maker',
      category: 'Electronics',
      image: '/images/products-img012.jpg',
      price: 15800,
      brand: 'PHILIPS ',
      rating: 4.5,
      numReviews: 15,
      countInStock: 30,
      description: 'Best coffee maker in the market',
    },
    {
      id: 13,
      name: 'Gift Diary',
      slug: 'gift-diary',
      category: 'Books',
      image: '/images/products-img013.jpg',
      price: 2000,
      brand: 'WYAIWYG ',
      rating: 3.5,
      numReviews: 2,
      countInStock: 9,
      description: 'Great gift for bookworms',
    },
    {
      id: 14,
      name: 'Pure Juice',
      slug: 'pure-juice',
      category: 'Food',
      image: '/images/products-img014.jpg',
      price: 3900,
      brand: 'CB ',
      rating: 4.5,
      numReviews: 15,
      countInStock: 30,
      description:
        'Purest and sweetest juice of life you can ever taste for that price',
    },
    {
      id: 15,
      name: 'Mary Lenn',
      slug: 'mary-lenn',
      category: 'Clothes',
      image: '/images/products-img015.jpg',
      price: 3500,
      brand: 'GUCCI ',
      rating: 4.5,
      numReviews: 15,
      countInStock: 30,
      description: 'Comfortable top and very beautiful',
    },
    {
      id: 16,
      name: 'Sessling',
      slug: 'sessling',
      category: 'Clothes',
      image: '/images/products-img016.jpg',
      price: 3800,
      brand: 'GUCCI ',
      rating: 4.5,
      numReviews: 15,
      countInStock: 30,
      description: 'Comfortable dress that goes for any occassion',
    },
  ],
};

export default data;
