import Head from 'next/head';
import Image from 'next/image';

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="text-lg text-green-900">
        <h1>Hello</h1>
      </div>
    </div>
  );
}
